// <auto-generated />
using System;
using AIS.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIS.DAL.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220228111130_addQuestionAreasQuestionSets")]
    partial class addQuestionAreasQuestionSets
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AIS.DAL.Entities.CompanyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("AIS.DAL.Entities.EmployeeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("AIS.DAL.Entities.IntervieweeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AppliesFor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AppliesFor");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Interviewees");
                });

            modelBuilder.Entity("AIS.DAL.Entities.QuestionAreaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("QuestionAreas");
                });

            modelBuilder.Entity("AIS.DAL.Entities.QuestionAreasQuestionSetsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("QuestionAreaId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionSetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionAreaId");

                    b.HasIndex("QuestionSetId");

                    b.ToTable("QuestionAreasQuestionSets");
                });

            modelBuilder.Entity("AIS.DAL.Entities.QuestionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("QuestionSetId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionSetId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("AIS.DAL.Entities.QuestionIntervieweeAnswerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Mark")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int?>("SessionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SessionId");

                    b.ToTable("QuestionIntervieweeAnswers");
                });

            modelBuilder.Entity("AIS.DAL.Entities.QuestionSetEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("QuestionSets");
                });

            modelBuilder.Entity("AIS.DAL.Entities.SessionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IntervieweeId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionAreaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("IntervieweeId");

                    b.HasIndex("QuestionAreaId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("AIS.DAL.Entities.TrueAnswerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId")
                        .IsUnique();

                    b.ToTable("TrueAnswers");
                });

            modelBuilder.Entity("AIS.DAL.Entities.EmployeeEntity", b =>
                {
                    b.HasOne("AIS.DAL.Entities.CompanyEntity", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("AIS.DAL.Entities.IntervieweeEntity", b =>
                {
                    b.HasOne("AIS.DAL.Entities.CompanyEntity", "Company")
                        .WithMany("Interviewees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("AIS.DAL.Entities.QuestionAreasQuestionSetsEntity", b =>
                {
                    b.HasOne("AIS.DAL.Entities.QuestionAreaEntity", "QuestionArea")
                        .WithMany("QuestionAreasQuestionSets")
                        .HasForeignKey("QuestionAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIS.DAL.Entities.QuestionSetEntity", "QuestionSet")
                        .WithMany("QuestionAreasQuestionSets")
                        .HasForeignKey("QuestionSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionArea");

                    b.Navigation("QuestionSet");
                });

            modelBuilder.Entity("AIS.DAL.Entities.QuestionEntity", b =>
                {
                    b.HasOne("AIS.DAL.Entities.QuestionSetEntity", "QuestionSet")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionSet");
                });

            modelBuilder.Entity("AIS.DAL.Entities.QuestionIntervieweeAnswerEntity", b =>
                {
                    b.HasOne("AIS.DAL.Entities.QuestionEntity", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIS.DAL.Entities.SessionEntity", "Session")
                        .WithMany("QuestionIntervieweeAnswers")
                        .HasForeignKey("SessionId");

                    b.Navigation("Question");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AIS.DAL.Entities.SessionEntity", b =>
                {
                    b.HasOne("AIS.DAL.Entities.EmployeeEntity", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIS.DAL.Entities.IntervieweeEntity", "Interviewee")
                        .WithMany()
                        .HasForeignKey("IntervieweeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIS.DAL.Entities.QuestionAreaEntity", "QuestionArea")
                        .WithMany()
                        .HasForeignKey("QuestionAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Interviewee");

                    b.Navigation("QuestionArea");
                });

            modelBuilder.Entity("AIS.DAL.Entities.TrueAnswerEntity", b =>
                {
                    b.HasOne("AIS.DAL.Entities.QuestionEntity", "Question")
                        .WithOne("TrueAnswer")
                        .HasForeignKey("AIS.DAL.Entities.TrueAnswerEntity", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("AIS.DAL.Entities.CompanyEntity", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Interviewees");
                });

            modelBuilder.Entity("AIS.DAL.Entities.QuestionAreaEntity", b =>
                {
                    b.Navigation("QuestionAreasQuestionSets");
                });

            modelBuilder.Entity("AIS.DAL.Entities.QuestionEntity", b =>
                {
                    b.Navigation("TrueAnswer");
                });

            modelBuilder.Entity("AIS.DAL.Entities.QuestionSetEntity", b =>
                {
                    b.Navigation("QuestionAreasQuestionSets");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("AIS.DAL.Entities.SessionEntity", b =>
                {
                    b.Navigation("QuestionIntervieweeAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
